CREATE DATABASE IF NOT EXISTS pembelian_mobil;
USE pembelian_mobil;

CREATE TABLE IF NOT EXISTS pembeli (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nama VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL,
    nomor VARCHAR(20) NOT NULL,
    mobil VARCHAR(50) NOT NULL,
    alamat TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
